dist: xenial
language: python
python:
- '2.7'
services:
- docker
env:
  global:
  - AZURE_ACR_URI="workonline.azurecr.io"
  - AZURE_ACR_TOKEN_NAME="travis-ci-eos-prefix-list-agent"
  # AZURE_ACR_TOKEN
  - secure: "IsXsMf9pRjW9abbFy4Hdjy6tvMexVmZGe+5kXblJ2Rfepnkv9PdEw+OyjUe8wz2Wf3hZqINECVjfzqHOI3Rae63S+aZqGxRrns+WJafIJK1MpwAI+h4SXcFgAL9zFGmFnO3grYkG8R06jLsVx2hmGqzivAZDYwxmZ9xZJYP4eFTV8HKUlpcHxLQzRCIg3gDABB/GCFERayNusFTfMFBxs2ZQ++A3DMgek9muQhhAPPr2i0/wEG0WGtrVRSP0eTQOdL7de1oPjSOL+kukMlJxlsbI3vyC70D0AL/EXLrkzXcngjPMzqJ6Yy9qo/Z44T8WxELLVT/4Q5PmA2uwfrH7JMqOeUlDeq5NgmrfkFd8nBQ5RCjGHBvrU9A3mqGGth946UunEJjR2k6tCDhMOXyFdFLKM6IeIhWR5oHpheOfI2HlTxMjUSHP0efblMkMQ3rQM26uMwjQ2hWvz38oTTuszc2bT69YiznY+fxmQE0yNO/oSEqD8c+NTWBorWKSJtVQWCThz6jpYWoD8tlwyvghLKVDg9f9X1wytILBOrN7cFo/mJP36Lm4uFOICY9EDgzXZlGZcTc83Dgnm1ibT5R8mS9vPhMo0lvY8/A5e8soam1dJkA7ya3MJjHNvuSTMFLiU4qaf88y+fjX2LSw78csxNFQbynKMOr4HbTifO373+4="
  matrix:
  - CEOS_VERSION="4.21.5F"
  - CEOS_VERSION="4.22.4M"
  - CEOS_VERSION="4.24.0F"
  - CEOS_VERSION="latest"
matrix:
  fast_finish: true
before_install:
- export PIP_PREFIX="${VIRTUAL_ENV}"
- pip install --upgrade pip setuptools codecov
- echo -n "${AZURE_ACR_TOKEN}" | docker login --username "${AZURE_ACR_TOKEN_NAME}" --password-stdin "${AZURE_ACR_URI}"
install:
- IMAGE_ID="$(docker build --build-arg REGISTRY="${AZURE_ACR_URI}" --build-arg VERSION="${CEOS_VERSION}" --quiet .)"
- CONTAINER_ID="$(docker run --detach --privileged --rm "${IMAGE_ID}")"
script:
- docker exec --interactive --tty "${CONTAINER_ID}" pytest
after_success:
- docker cp "${CONTAINER_ID}:/root/coverage.xml" "./"
- codecov -e CEOS_VERSION
before_deploy:
- sudo apt-get update -q
- sudo apt-get install -y rpm
- mkdir -p bdist_rpm
deploy:
- provider: pypi
  distributions: sdist bdist_wheel bdist_rpm
  user: __token__
  password:
    secure: h97BXyndv9HiCs4L/qRyx2JIIV+peQdZiOW5Zc4aMbQWrTnlgV163h2LZ9V7SzS9Kwk7EnWsAgyLzVp9mJI1Rnc+r8RQQ56D7bcrDogSZnW/qxgGEv+XbEg3aC4IbdnOKMFQWFU4i4rt0Bu+MAAJUwnIOiJ4gbyVKqmYzFoPmPBVAJMC1BOZd3Gr5BblxQzjibi8mVIGNVx3iB7n/mlBqmn1wPii8nccYoNTUtqU6+k0lxCH/5HdRvqXgrZMRM0Jh3n4Y0rGuwxl+EwnqB58jXGc3cFMYrB6ZEWiOC6ZfdWegOdSD5hMuffZ50zZ3yYd5Ii282Yj74eT8r7W90fxLhpsEg3Z4RwZPPtgLUEiHolCJ/G+66utGlHbVEg/JhUjR+equNejH7Tf9igoLYc1G1aaiGUI83CDjFSJH0XakyczUhHKr7PZ8hLPvzTg7DNGyovy7sEuP2PWHKKYlw+zncGBN78ytnX0mJCwgnx4UdZwnbqC8jUZnDbXJKuK8Em2VMFOIF3FjgdDoKDu1J/UOZhuT6neIUwidJeCS2o5LohQktDro6lfwCyu1n5M1ZuSZXU3XHo53Tjm+1qIl6RLmKRnqfYJoNBHFfY0OqGG4Ft0b3JxyULleZA6XtCNNdU5aNJ1yb08Mkvx5PP91R57bmlN8hk27c9ybIwXMe6enSQ=
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    python: '2.7'
    condition: "$CEOS_VERSION = latest"
- provider: releases
  api_key:
    secure: ehKR+Ze6T9ns7e+n5vfRNFFsl62Endugyda0eue9nWuW1LElTLO1JPEQySTXHuo5PkwG0aw+qbJMT6EN9lIJUPL0R9e3hw0CH0GhgR7wBM9d3itpF5Qcnd/wO0XX+kyh8pklu5J/qZ1fSfQGVPs6Qpn5Mx0bHcCHsl52i7xqM+3kyN7rzoTZkZC22obv5NO2SVlMcNquAcES38mFaz/eeV03XGRSL7w2X7mpwIilt3MEOYbDOLMv9Rk0cg/jSZZ6Dnc9vAaMaYtcFKuDqG7PmjDVgKiCd03Wz9aLg5aS37NFOJ/vA0L/v6cxMhkzOg1733wRZaSGQ7SG58z8Yrmk4+yD3dibKWzsshHEMHYQiIWSOBWG3sgTi8olzrnvLSEow69tzOXTs01bs0cjZuyX6ydT3x1NG20v1kBoHaxEWtGKDb5MNkg/69sb5Iz3huYeYcHfY+Tq5i6O+73k9H9NJjllwJ4IkOeBAeFgJHdfjWqtely2OcnRiKpnqUtUliCEkuzEln8SK71o1lKOgTy2r6804eWV9NZwLSyWm3E+SfEfpVnKCfLOe7rS7PtS0yAgicUcmGnYqeXoSlyj5o0i+KGZWTjJF/Jks5uimt+WmU2OLboi6eTvx0ramfq6gozSF+6r16zV2VVjUAE6YPGEkfI1+AUnlIrQUo1NtlsqddQ=
  file_glob: true
  file:
  - dist/*
  - bdist_rpm/*
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    python: '2.7'
    condition: "$CEOS_VERSION = latest"
after_script:
- docker kill "${CONTAINER_ID}"
- docker image rm "${IMAGE_ID}"
notifications:
  email: false
