dist: xenial
language: python
python:
- '2.7'
services:
- docker
env:
  global:
  - AZURE_ACR_URI="workonline.azurecr.io"
  - AZURE_ACR_APPID="99d33495-51d7-4c2e-bb15-70f33ba25587"
  # AZURE_ACR_PASSWD=
  - secure: D/Uuj1G+Pd1yjhN+l0u3USNDPt0BsY0o+e4oaFn+3BXhVIWUbc1NNPMg7nvjpHLiF9lm2SBchJvte04eWjRFsoKgZhleoH2q+Y7QUrGQHlITLVgtCg8DiWAeR0c3j6tHqt6Qei16owuNZ3h4ELkwOOR0wFET92De7w/GZccISX/suw4yKaWq0rNIkB4Yzql+k82sip7CTVRaHdpSb+3PV0wEVqL2iruReR2eyaiE04cE36mW+/3DyoVp2ybNnkFXLphPZQ/n+ZuRdNwPqSHbzwNAUBmq0pd67fvgd2s4aJNmbVBJIy6VdzpgsAfW9zKPeqB1yejU9zDhDlLO2i8/nDlRKlBWH0PqpwmsM0kJUTH8UKYbIfA6J34I3AC8wDftI7YdfO66b4UKqUhDwDAUQyoeiAdSFELmxUCVk2V+W/j5r7lZM+f/cvWqulDhIm0Vvqlw3fQEDJPRImlsnmptBKDUOd13NaXlLhr2TE/S3Puwaf0/grQjnkufvxAT79k9MzkWURzcRJ5caFFZFSvJ6faNbiEnjUkJcP+LA+Ct9JTmGtuOAw7FnzweCrYIFK/G43MGFOQjI8g0cKnVdFdsOIBqSLnPLbeUF/iXC2RojeZGsXxGYIXoMa5XS4GzURuHOWSV1rlaqP1/zLJ63d9RaeSI/A+OoZ6m1uzMIrc4HFw=
  matrix:
  - CEOS_VERSION="4.21.5F"
  - CEOS_VERSION="4.22.4M"
  - CEOS_VERSION="4.24.0F"
  - CEOS_VERSION="latest"
matrix:
  fast_finish: true
before_install:
- export PIP_PREFIX="${VIRTUAL_ENV}"
- pip install --upgrade pip setuptools codecov
- echo -n "${AZURE_ACR_PASSWD}" | docker login --username "${AZURE_ACR_APPID}" --password-stdin "${AZURE_ACR_URI}"
install:
- IMAGE_ID="$(docker build --build-arg REGISTRY="${AZURE_ACR_URI}" --build-arg VERSION="${CEOS_VERSION}" --quiet .)"
- CONTAINER_ID="$(docker run --detach --privileged --rm "${IMAGE_ID}")"
script:
- docker exec --interactive --tty "${CONTAINER_ID}" pytest
after_success:
- docker cp "${CONTAINER_ID}:/root/coverage.xml" "./"
- codecov -e CEOS_VERSION
before_deploy:
- sudo apt-get update -q
- sudo apt-get install -y rpm
- mkdir -p bdist_rpm
deploy:
- provider: pypi
  distributions: sdist bdist_wheel bdist_rpm
  user: __token__
  password:
    secure: h97BXyndv9HiCs4L/qRyx2JIIV+peQdZiOW5Zc4aMbQWrTnlgV163h2LZ9V7SzS9Kwk7EnWsAgyLzVp9mJI1Rnc+r8RQQ56D7bcrDogSZnW/qxgGEv+XbEg3aC4IbdnOKMFQWFU4i4rt0Bu+MAAJUwnIOiJ4gbyVKqmYzFoPmPBVAJMC1BOZd3Gr5BblxQzjibi8mVIGNVx3iB7n/mlBqmn1wPii8nccYoNTUtqU6+k0lxCH/5HdRvqXgrZMRM0Jh3n4Y0rGuwxl+EwnqB58jXGc3cFMYrB6ZEWiOC6ZfdWegOdSD5hMuffZ50zZ3yYd5Ii282Yj74eT8r7W90fxLhpsEg3Z4RwZPPtgLUEiHolCJ/G+66utGlHbVEg/JhUjR+equNejH7Tf9igoLYc1G1aaiGUI83CDjFSJH0XakyczUhHKr7PZ8hLPvzTg7DNGyovy7sEuP2PWHKKYlw+zncGBN78ytnX0mJCwgnx4UdZwnbqC8jUZnDbXJKuK8Em2VMFOIF3FjgdDoKDu1J/UOZhuT6neIUwidJeCS2o5LohQktDro6lfwCyu1n5M1ZuSZXU3XHo53Tjm+1qIl6RLmKRnqfYJoNBHFfY0OqGG4Ft0b3JxyULleZA6XtCNNdU5aNJ1yb08Mkvx5PP91R57bmlN8hk27c9ybIwXMe6enSQ=
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    python: '2.7'
    condition: "$CEOS_VERSION = latest"
- provider: releases
  api_key:
    secure: ehKR+Ze6T9ns7e+n5vfRNFFsl62Endugyda0eue9nWuW1LElTLO1JPEQySTXHuo5PkwG0aw+qbJMT6EN9lIJUPL0R9e3hw0CH0GhgR7wBM9d3itpF5Qcnd/wO0XX+kyh8pklu5J/qZ1fSfQGVPs6Qpn5Mx0bHcCHsl52i7xqM+3kyN7rzoTZkZC22obv5NO2SVlMcNquAcES38mFaz/eeV03XGRSL7w2X7mpwIilt3MEOYbDOLMv9Rk0cg/jSZZ6Dnc9vAaMaYtcFKuDqG7PmjDVgKiCd03Wz9aLg5aS37NFOJ/vA0L/v6cxMhkzOg1733wRZaSGQ7SG58z8Yrmk4+yD3dibKWzsshHEMHYQiIWSOBWG3sgTi8olzrnvLSEow69tzOXTs01bs0cjZuyX6ydT3x1NG20v1kBoHaxEWtGKDb5MNkg/69sb5Iz3huYeYcHfY+Tq5i6O+73k9H9NJjllwJ4IkOeBAeFgJHdfjWqtely2OcnRiKpnqUtUliCEkuzEln8SK71o1lKOgTy2r6804eWV9NZwLSyWm3E+SfEfpVnKCfLOe7rS7PtS0yAgicUcmGnYqeXoSlyj5o0i+KGZWTjJF/Jks5uimt+WmU2OLboi6eTvx0ramfq6gozSF+6r16zV2VVjUAE6YPGEkfI1+AUnlIrQUo1NtlsqddQ=
  file_glob: true
  file:
  - dist/*
  - bdist_rpm/*
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    python: '2.7'
    condition: "$CEOS_VERSION = latest"
after_script:
- docker kill "${CONTAINER_ID}"
- docker image rm "${IMAGE_ID}"
notifications:
  email: false
