dist: xenial
language: python
python:
- '2.7'
services:
- docker
env:
  global:
  - AZURE_ACR_URI="workonline.azurecr.io"
  - AZURE_ACR_APPID="99d33495-51d7-4c2e-bb15-70f33ba25587"
  # AZURE_ACR_PASSWD=
  - secure: DgE0F2bj3fR3d2R0B5M4DdS1H7L1LoglO+EiO5LGuiqu75UKMLGqfSWZubddI/htk702KTDu46kp0olmIhGvSEAh3CkOZIM9oNjvW1YalMt/ydCG35zHA1gK70RcHQHtFICi0zusFbjorHIHrwXSWJo8AKqwabTvxP8F5N8qunGjQbj6PeM82h9n1oyQ8n7R6K1X4cAIRhzyidK74AKLYwujpbnV9vQDBx4rlAukRaXXFJgJQTeSWabfLDlIyqo9Wmb1PmpluiDEnz1BXZp0QjRnbdRh99ApuW3OH1Td0rCqveeEYn+ejHMKdEWZ+v+haT2shb5NT3CAI9d+nvJtDgdA1dHOYdVIPSMjw6Mn7Kzrdun3wc6kc9ViqHy5lWbg6bm8P9Va74Cc+sAyrSRMLG21lhcrzvkVa65NW/HiJYFwfnjLIxgWEtsgDzLLYN1AVMaZ7SsQHgDr59IZtVmCm/5BM0eBcSxqnrmUvit38xrcE5BaCWEzNFsUZAcZDRveAKKH511uRPz+9Pth+p66bmbIL+J08vSz8oEqeJXoPrKZImq6FTiOxKNu93nTkS6odtNJuumOp98vLX/8c0ni8R/0MdYIKNjTCLSWcMQ9s+scZBg664FkFpAZuAo19BxoXuzZdxkTFFwmw4818EZjtyPuXq5yoiDXPt2CsSj60LU=
  matrix:
  - CEOS_VERSION="4.21.0F"
  - CEOS_VERSION="4.21.2F"
matrix:
  fast_finish: true
before_install:
- sudo pip install --upgrade pip setuptools codecov
- echo -n "${AZURE_ACR_PASSWD}" | docker login --username "${AZURE_ACR_APPID}" --password-stdin "${AZURE_ACR_URI}"
install:
- IMAGE_ID="$(docker build --build-arg REGISTRY="${AZURE_ACR_URI}" --build-arg VERSION="${CEOS_VERSION}" --quiet .)"
- CONTAINER_ID="$(docker run --detatch --privileged --rm "${IMAGE_ID}")"
script:
- docker exec --interactive --tty "${CONTAINER_ID}" pytest
after_success:
- docker cp "${CONTAINER_ID}:/root/coverage.xml" "./"
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: benmaddison
  password:
    secure: B7OR/gVGIJXrXedelZ2cGbENHOsqulshoLh8gPeMz11lFEgjMJSXU4/dECeFzlhvcksBd2eRydlQNfkN1ZGaoF6OOa7N/FZftKhOO8DlfSagq6/Vxo3ZUT8Pf4icpgQP3TbD85JVqq6Z4MZYmCCNKntiqkzT0jGSCL9nEKZeFC2RmL9gVN3FBtowZ5BX+7xLg33zgdAByGi6r5UmMlW38IepU6G1OJkqIZsa7YfMxvbi13CE0Wa6paZ1g5QqE/9LgRxvuLLzAV1M6IhjIgz95B9yMehQQalqXJxCBw5HuRVYlXfDxjPErwO1FhD++wwy0Ne8qIeo2regxlHnk2Mpp7NdM4y1FBC0ipW/c4guGmo4G32uvr1O/DaD53B/K2BEjmsel/gn/udmjYLp+zFIrpadzIZR9aWSDYn0jLv2V+rbEfXs/38BsNxAhUrhyE4cN6CpB2ojR7al+0AnoLjrKA4QVvlnryJ5go5FVguNmGsyzy1QOXYS6b9hCUoatr7JBBiNEiIke+usbPqbHWX/tmTklzOklxo0B7SrJja9re2b5ou8ZmPQY2Z2Y3cqMAg0P4H6kSgh2FnjzwPzVPpYxoCUgjQjTWVjmzkLeubdvvEzsmXEDup4bA0q7yB7pS9VnvMeKzFAH4xjeaTxZhly64adTjItU9t3xJztAVi9v74=
  on:
    tags: true
    python: '2.7'
after_script:
- docker kill "${CONTAINER_ID}"
- docker image rm "${IMAGE_ID}"
