name: earthly
description: "Run an earthly target"
inputs:
  earthly_version:
    description: "earthly release version"
    required: false
    default: "0.6.2"
  target:
    description: "earthly target to run"
    required: true
  ghcr_token:
    description: "ghcr authentication token"
    required: true
  acr_uri:
    description: "acr uri"
    required: false
    default: "workonline.azurecr.io"
  acr_token_name:
    description: "acr authentication token name"
    required: false
    default: "gh-actions-eos-prefix-list-agent"
  acr_token:
    description: "acr authentication token"
    required: true
runs:
  using: composite
  steps:
    - name: install earthly
      shell: bash
      run: |
        sudo wget "https://github.com/earthly/earthly/releases/download/v${{ inputs.earthly_version }}/earthly-linux-amd64" \
          -O /usr/local/bin/earthly && \
        sudo chmod +x /usr/local/bin/earthly
    - name: bootstrap earthly
      shell: bash
      run: /usr/local/bin/earthly bootstrap
    - name: login to azure acr
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.acr_uri }}
        username: ${{ inputs.acr_token_name }}
        password: ${{ inputs.acr_token }}
    - name: login to ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr_token }}
    - name: build
      shell: bash
      run: earthly -P --ci --output --push +${{ inputs.target }}
